<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <RootNamespace>VRT.Downloaders</RootNamespace>
  </PropertyGroup>

  <ItemGroup>    
    <PackageReference Include="CommunityToolkit.Mvvm" />    
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	<PackageReference Include="DynamicData" />
	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	<PackageReference Include="Microsoft.Extensions.Options" />
	<PackageReference Include="ReactiveUI" />    
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VRT.Downloaders.Common\VRT.Downloaders.Common.csproj" />
    <ProjectReference Include="..\VRT.Downloaders.Services.Medias\VRT.Downloaders.Services.Medias.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
