<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>	
    <RootNamespace>VRT.Downloaders</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>
</Project>
