<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="YoutubeExplode" />
    <PackageReference Include="YoutubeExplode.Converter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VRT.Downloaders.Services.Medias\VRT.Downloaders.Services.Medias.csproj" />
  </ItemGroup>

</Project>
