//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRT.Downloaders.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRT.Downloaders.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task cannot be canceled.
        /// </summary>
        public static string Error_CannotCancelTask {
            get {
                return ResourceManager.GetString("Error_CannotCancelTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}.
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect resource Url.
        /// </summary>
        public static string Error_IncorrectResourceUrl {
            get {
                return ResourceManager.GetString("Error_IncorrectResourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} can not be performed. {1}.
        /// </summary>
        public static string Error_MethodNotSupported_Name_Reason {
            get {
                return ResourceManager.GetString("Error_MethodNotSupported_Name_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        public static string Error_NotSupported {
            get {
                return ResourceManager.GetString("Error_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partitions not created.
        /// </summary>
        public static string Error_PartitionsNotCreated {
            get {
                return ResourceManager.GetString("Error_PartitionsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size must be greater than zero.
        /// </summary>
        public static string Error_SizeMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Error_SizeMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State {0} already set.
        /// </summary>
        public static string Error_StateAlreadySet_StateName {
            get {
                return ResourceManager.GetString("Error_StateAlreadySet_StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is already on the download list.
        /// </summary>
        public static string Error_TaskAlreadyOnDownloadList {
            get {
                return ResourceManager.GetString("Error_TaskAlreadyOnDownloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download task cannot be null.
        /// </summary>
        public static string Error_TaskCannotBeNull {
            get {
                return ResourceManager.GetString("Error_TaskCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download canceled.
        /// </summary>
        public static string Info_DownloadCanceled {
            get {
                return ResourceManager.GetString("Info_DownloadCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download in progress.
        /// </summary>
        public static string Info_DownloadInProgress {
            get {
                return ResourceManager.GetString("Info_DownloadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Msg_Success {
            get {
                return ResourceManager.GetString("Msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Title_Downloads {
            get {
                return ResourceManager.GetString("Title_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
    }
}
